from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('ledmatrixclient', src, depend = ['LEDMATRIXCLIENT_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
