from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('ledmatrixclient', src, depend = ['PKG_USING_LEDMATRIXCLIENT'], CPPPATH = CPPPATH)

Return('group')
